// Generated by CoffeeScript 1.9.1
(function() {
  var Model, PostSetAction;

  Model = require('./model').Model;

  PostSetAction = require('./postsetaction').PostSetAction;

  module.exports = {
    Model: Model,
    PostSetAction: PostSetAction
  };

}).call(this);
