// Generated by CoffeeScript 1.9.1
(function() {
  var Model, PostSetAction, capitalizeFirstLetter, getGetterName, getPropertyNameOfSetter, getSetterName, lowercaseFirstLetter, startsWith;

  capitalizeFirstLetter = function(string) {
    return string.charAt(0).toUpperCase() + string.slice(1);
  };

  lowercaseFirstLetter = function(string) {
    return string.charAt(0).toLowerCase() + string.slice(1);
  };

  startsWith = function(candidate, query) {
    return candidate.indexOf(query) === 0;
  };

  getSetterName = function(propertyName) {
    var upperCasePropertyName;
    upperCasePropertyName = capitalizeFirstLetter(propertyName);
    return 'set' + upperCasePropertyName;
  };

  getGetterName = function(propertyName) {
    var upperCasePropertyName;
    upperCasePropertyName = capitalizeFirstLetter(propertyName);
    return 'get' + upperCasePropertyName;
  };

  getPropertyNameOfSetter = function(setterName) {
    return lowercaseFirstLetter(setterName.slice(3));
  };

  Model = function(modelClass) {
    var createFromMap, createGetterIfNeeded, createProperty, createSetterIfNeeded, createToMap, fn, i, len, listSortedPropertyNames, propertyName, propertyNames, prototype;
    prototype = modelClass.prototype;
    listSortedPropertyNames = function() {
      var propertyKey, propertyNames, propertyValue;
      propertyNames = [];
      for (propertyKey in prototype) {
        propertyValue = prototype[propertyKey];
        if (!(propertyValue instanceof Function)) {
          propertyNames.push(propertyKey.substr(1));
        }
      }
      propertyNames = propertyNames.sort();
      return propertyNames;
    };
    createSetterIfNeeded = function(propertyName) {
      var setterName;
      setterName = getSetterName(propertyName);
      if (!prototype[setterName]) {
        prototype[setterName] = function(value) {
          return this["_" + propertyName] = value;
        };
      }
      return prototype[setterName];
    };
    createGetterIfNeeded = function(propertyName) {
      var getterName;
      getterName = getGetterName(propertyName);
      if (!prototype[getterName]) {
        prototype[getterName] = function(value) {
          return this["_" + propertyName];
        };
      }
      return prototype[getterName];
    };
    createProperty = function(propertyName) {
      return prototype[propertyName] = function(value) {
        if (arguments.length > 0) {
          return this[getSetterName(propertyName)](value);
        } else {
          return this[getGetterName(propertyName)]();
        }
      };
    };
    createFromMap = function() {
      return prototype.fromMap = function(propertyMap) {
        var i, len, propertyName, propertyNames, propertyValue, results, setterName;
        if (propertyMap == null) {
          propertyMap = {};
        }
        propertyNames = listSortedPropertyNames();
        results = [];
        for (i = 0, len = propertyNames.length; i < len; i++) {
          propertyName = propertyNames[i];
          propertyValue = propertyMap[propertyName];
          setterName = getSetterName(propertyName);
          if (propertyValue != null) {
            results.push(this[setterName](propertyValue));
          } else {
            results.push(void 0);
          }
        }
        return results;
      };
    };
    createToMap = function() {
      return prototype.toMap = function() {
        var getterName, i, len, propertyMap, propertyName, propertyNames, propertyValue;
        propertyMap = {};
        propertyNames = listSortedPropertyNames();
        for (i = 0, len = propertyNames.length; i < len; i++) {
          propertyName = propertyNames[i];
          getterName = getGetterName(propertyName);
          propertyValue = this[getterName]();
          propertyMap[propertyName] = propertyValue;
        }
        return propertyMap;
      };
    };
    propertyNames = listSortedPropertyNames(prototype);
    fn = function(propertyName) {
      createGetterIfNeeded(propertyName);
      createSetterIfNeeded(propertyName);
      return createProperty(propertyName);
    };
    for (i = 0, len = propertyNames.length; i < len; i++) {
      propertyName = propertyNames[i];
      fn(propertyName);
    }
    createFromMap();
    createToMap();
    return prototype;
  };

  PostSetAction = function(prototype, action) {
    var fn, i, len, listSetterNames, postExtendSetter, ref, setterName;
    listSetterNames = function() {
      var propertyKey, propertyValue, setterNames;
      setterNames = [];
      for (propertyKey in prototype) {
        propertyValue = prototype[propertyKey];
        if (startsWith(propertyKey, "set")) {
          setterNames.push(propertyKey);
        }
      }
      return setterNames;
    };
    postExtendSetter = function(setterName, extension) {
      var originalSetter;
      originalSetter = prototype[setterName];
      return prototype[setterName] = function(newValue) {
        var oldValue, propertyName;
        propertyName = getPropertyNameOfSetter(setterName);
        oldValue = this["_" + propertyName];
        originalSetter.apply(this, [newValue]);
        extension.apply(this, [propertyName, newValue, oldValue]);
        return newValue;
      };
    };
    ref = listSetterNames();
    fn = function(setterName) {
      return postExtendSetter(setterName, action);
    };
    for (i = 0, len = ref.length; i < len; i++) {
      setterName = ref[i];
      fn(setterName);
    }
    return prototype;
  };

  module.exports = {
    Model: Model,
    PostSetAction: PostSetAction
  };

}).call(this);
