// Generated by CoffeeScript 1.9.3
(function() {
  var Model, getGetterName, getPropertiesForAccessorCreation, getSetterName, isPropertyForAccessorCreation, removeFirstChar, uppercaseFirstChar;

  removeFirstChar = function(string) {
    return string.slice(1);
  };

  uppercaseFirstChar = function(string) {
    return string.charAt(0).toUpperCase() + removeFirstChar(string);
  };

  exports.getSetterName = getSetterName = function(propertyName) {
    return "set" + (uppercaseFirstChar(propertyName));
  };

  exports.getGetterName = getGetterName = function(propertyName) {
    return "get" + (uppercaseFirstChar(propertyName));
  };

  isPropertyForAccessorCreation = function(propertyName, propertyValue) {
    return (!(propertyValue instanceof Function)) && (propertyName.charAt(0) === '_');
  };

  getPropertiesForAccessorCreation = function(prototype) {
    var propertyName, propertyNames, propertyValue;
    propertyNames = (function() {
      var results;
      results = [];
      for (propertyName in prototype) {
        propertyValue = prototype[propertyName];
        if (isPropertyForAccessorCreation(propertyName, propertyValue)) {
          results.push(removeFirstChar(propertyName));
        }
      }
      return results;
    })();
    propertyNames = propertyNames.sort();
    return propertyNames;
  };

  Model = function(prototype) {
    var createFromMap, createFromMapBypassSetters, createGetterIfNeeded, createProperty, createSetterIfNeeded, createToMap, i, len, propertiesWithAccessors, propertyName;
    propertiesWithAccessors = getPropertiesForAccessorCreation(prototype);
    createSetterIfNeeded = function(propertyName) {
      var name;
      return prototype[name = getSetterName(propertyName)] != null ? prototype[name] : prototype[name] = function(value) {
        return this["_" + propertyName] = value;
      };
    };
    createGetterIfNeeded = function(propertyName) {
      var name;
      return prototype[name = getGetterName(propertyName)] != null ? prototype[name] : prototype[name] = function(value) {
        return this["_" + propertyName];
      };
    };
    createProperty = function(propertyName) {
      return prototype[propertyName] = function(value) {
        if (arguments.length > 0) {
          return this[getSetterName(propertyName)](value);
        } else {
          return this[getGetterName(propertyName)]();
        }
      };
    };
    createFromMap = function() {
      return prototype.fromMap = function(propertyMap) {
        var i, len, propertyName, results;
        if (propertyMap == null) {
          propertyMap = {};
        }
        results = [];
        for (i = 0, len = propertiesWithAccessors.length; i < len; i++) {
          propertyName = propertiesWithAccessors[i];
          if (propertyName in propertyMap) {
            results.push(this[getSetterName(propertyName)](propertyMap[propertyName]));
          }
        }
        return results;
      };
    };
    createToMap = function() {
      return prototype.toMap = function() {
        var i, len, propertyMap, propertyName;
        propertyMap = {};
        for (i = 0, len = propertiesWithAccessors.length; i < len; i++) {
          propertyName = propertiesWithAccessors[i];
          propertyMap[propertyName] = this[getGetterName(propertyName)]();
        }
        return propertyMap;
      };
    };
    createFromMapBypassSetters = function() {
      return prototype.fromMapBypassSetters = function(propertyMap) {
        var i, len, propertyName, results;
        if (propertyMap == null) {
          propertyMap = {};
        }
        results = [];
        for (i = 0, len = propertiesWithAccessors.length; i < len; i++) {
          propertyName = propertiesWithAccessors[i];
          if (propertyName in propertyMap) {
            results.push(this["_" + propertyName] = propertyMap[propertyName]);
          }
        }
        return results;
      };
    };
    for (i = 0, len = propertiesWithAccessors.length; i < len; i++) {
      propertyName = propertiesWithAccessors[i];
      createGetterIfNeeded(propertyName);
      createSetterIfNeeded(propertyName);
      createProperty(propertyName);
    }
    createFromMap();
    createToMap();
    createFromMapBypassSetters();
    return prototype;
  };

  exports.Model = Model;

}).call(this);
