// Generated by CoffeeScript 1.9.3
(function() {
  var PostSetAction, getPropertyNameOfSetter, lowercaseFirstChar, startsWith;

  lowercaseFirstChar = function(string) {
    return string.charAt(0).toLowerCase() + string.slice(1);
  };

  getPropertyNameOfSetter = function(setterName) {
    return lowercaseFirstChar(setterName.slice(3));
  };

  startsWith = function(string, prefix) {
    return string.indexOf(prefix) === 0;
  };

  PostSetAction = function(prototype, postSetHook) {
    var extendSetter, setterName;
    extendSetter = function(setterName) {
      var originalSetter;
      originalSetter = prototype[setterName];
      return prototype[setterName] = function(value) {
        var oldValue, propertyName;
        propertyName = getPropertyNameOfSetter(setterName);
        oldValue = this["_" + propertyName];
        originalSetter.call(this, value);
        postSetHook.call(this, propertyName, value, oldValue);
        return value;
      };
    };
    for (setterName in prototype) {
      if (startsWith(setterName, 'set')) {
        extendSetter(setterName);
      }
    }
    return prototype;
  };

  module.exports.PostSetAction = PostSetAction;

}).call(this);
